---
- name: Create tonuser
  user:
    name: "{{ ton_user }}"
    group: "{{ ton_group }}"

- git:
    repo: "https://github.com/tonlabs/main.ton.dev.git"
    dest: "{{ install_path }}/{{ ton_src }}/"

- name: Own tonuser
  file:
    path: "{{ install_path }}/{{ ton_src }}/"
    recurse: yes
    owner: "{{ ton_user }}"
    group: "{{ ton_group }}"

- name: Build node
  shell:
    cmd: source env.sh && ./build.sh
    chdir: /srv/main.ton.dev.git/scripts
  args:
    executable: /bin/bash

- name: Setup node
  shell:
    cmd: ./setup.sh
    chdir: "{{ install_path }}/{{ ton_src }}/scripts"
  args:
    executable: /bin/bash

- name: Check keys directory
  stat:
    path: "{{ install_path }}/ton-keys"
  register: keyfolder

- name: Generate keys
  shell:
    cmd: ./msig_genaddr.sh >> "{{ install_path }}/ton-keys/seed_phrase.secret"
    chdir: "{{ install_path }}/{{ ton_src }}/scripts"
  args:
    executable: /bin/bash
  when: keyfolder.stat.exists == false

# Add service
- name: Create Unit file
  template: src=freeton.service.j2 dest=/etc/systemd/system/freeton.service mode=644
  # notify:
  #   - reload systemctl
- name: Start freeton
  service: name=freeton.service state=started enabled=yes

# Add cronjob
- name: Cronjob for validator script
  cron:
    name: "validator script"
    minute: "*/10"
    cron_file: freeton_validator
    user: "{{ton_user}}"
    job: "{{ install_path }}/{{ ton_src }}/scripts/validator_msig.sh 10001 >> {{log_path}}/validator.log"

# Install jq for parse json
- name: Install jq
  apt:
    name: jq
    state: present

# Get public keycloak_client
- name: Get publickey
  shell:
    cmd: cat msig.keys.json | jq -r '.public'
    chdir: "{{ install_path }}/ton-keys"
  register: publickey
  args:
    executable: /bin/bash

# Deploy wallet
- name: Deploy wallet
  shell:
    cmd: ./tonos-cli deploy "{{ install_path }}/{{ ton_src }}/configs/SafeMultisigWallet.tvc '{"owners":["0x{{ publickey.stdout }}"],"reqConfirms":1}' --abi "{{ install_path }}/{{ ton_src }}/configs/SafeMultisigWallet.abi.json" --sign "{{ install_path }}/ton-keys/msig.keys.json" --wc -1
    chdir: "{{ install_path }}/{{ ton_src }}/ton/build/utils"
  args:
    executable: /bin/bash
  when: keyfolder.stat.exists == false
