---
# tasks file for prometheus-node-exporter

# Download prometheus-node-exporter
- name: Download prometheus node exporter binary
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz"
    dest: /tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz

# Unarchive prometheus-node-exporter
- name: Unarchive prometheus node exporter
  become: false
  unarchive:
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}/node_exporter"
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz"
    dest: "/tmp"

# Create user for prometheus-node-exporter
- name: Create prometheus_exporter_user
  user:
    name: "{{ prometheus_exporter_user }}"
    groups: "{{ prometheus_exporter_group }}"
    create_home: no
    shell: /bin/false
    system: true

# Put prometheus-node-exporter to work dir
- name: Copy file with owner and permissions
  copy:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: "{{ prometheus_exporter_user }}"
    group: "{{ prometheus_exporter_group }}"
    mode: "0755"

# Create service
- name: Create systemd service unit
  template:
    src: prometheus-node-exporter.service.j2
    dest: /etc/systemd/system/prometheus-node-exporter.service

# Check service
- name: Ensure prometheus node exporter service is enabled and started
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

# Remove temporary file
- name: Remove temporary files
  file:
    path: /tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz
    state: absent
