---
# The role contains common plays that will be run on all nodes.

- name: Update apt cache
  apt: update-cache=yes cache_valid_time=86400
  sudo: yes
---
# Upgrade System
- name: Update all packages
  apt: upgrade=dist
  sudo: yes

# Install packages
- name: install basic packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  tags: [packages]
  with_items:
    - nginx
    - ntp
    - mc
    - nmap
    - bmon
    - vnstat
    - git
    - monit
    - mtr-tiny
    - screen
    - wget
    - curl
    - sysstat
    - dnsutils
    - jq

- name: start ntp
  service: name=ntp state=started enabled=true
